//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//tnginamo isapanaga
namespace RestoReserveDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customerInfo()
        {
            this.reservationInfoes = new HashSet<reservationInfo>();
        }
    
        public long customer_id { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public long contact_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservationInfo> reservationInfoes { get; set; }
    }
}
