//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoReserveDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class restoReservationEntities1 : DbContext
    {
        public restoReservationEntities1()
            : base("name=restoReservationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customerInfo> customerInfoes { get; set; }
        public virtual DbSet<foodInfo> foodInfoes { get; set; }
        public virtual DbSet<orderInfo> orderInfoes { get; set; }
        public virtual DbSet<reservationInfo> reservationInfoes { get; set; }
    }
}
