//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoReserveDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderInfo
    {
        public long order_id { get; set; }
        public long reservation_id { get; set; }
        public long dish_id { get; set; }
        public int quantity { get; set; }
    
        public virtual foodInfo foodInfo { get; set; }
        public virtual reservationInfo reservationInfo { get; set; }
    }
}
