//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoReserveDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservationInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservationInfo()
        {
            this.orderInfoes = new HashSet<orderInfo>();
        }
    
        public long reservation_id { get; set; }
        public System.DateTime date_of_reservation { get; set; }
        public long number_of_guests { get; set; }
        public System.TimeSpan time_of_reservation { get; set; }
        public long customer_id { get; set; }
    
        public virtual customerInfo customerInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderInfo> orderInfoes { get; set; }
    }
}
